version: "3.9"

services:
  alia-queen:
    build: .
    image: alia-queen
    container_name: alia-queen
    networks:
      - bot
    env_file:
      - stack.env

networks:
  bot:
    name: alia-queen
